CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(50),
    signup_date DATE,
    gender VARCHAR(10),
    age INT
);
CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100),
    category VARCHAR(50),
    price NUMERIC(10,2),
    stock INT
);
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    product_id INT,
    quantity INT,
    unit_price NUMERIC(10,2),
    total_amount NUMERIC(10,2),
    payment_method VARCHAR(50),
    order_status VARCHAR(50),
    order_date DATE
);

SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM products;


--total customers in the dataset
select count(customer_id) as total_customers 
from customers;

--total orders placed
select count(order_id) as total_orders
from orders;

--total revenue generated
select round(sum(total_amount), 2) as total_revenue
from orders;

--monthly revenue trend
select extract(month from order_date) as month,
round(sum(total_amount), 2) as monthly_revenue
from orders
group by month
order by month;

--highest revenue generating month
select 
extract(month from order_date) as month,
round(sum(total_amount), 2) as total_revenue
from orders
group by month
order by total_revenue desc
limit 1;

--revenue generated by each payment method
select 
payment_method,
round(sum(total_amount), 2) as total_revenue
from orders
group by payment_method
order by total_revenue desc;


--top 5 customers by spending
select c.customer_name,round(sum(o.total_amount), 2) as total_spent
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_name
order by total_spent desc
limit 5;

--top 5 customers by spending
select 
c.customer_name,
round(sum(o.total_amount), 2) as total_spent
from customers c
join orders o
on c.customer_id = o.customer_id
group by c.customer_name
order by total_spent desc
limit 5;



